### ISSUE TITLE
AppDynamics Partner Docs Landing Page Needs a Refresh

### ISSUE THREAD

**Issue by radhikapc** [pivotal-cf/docs-appdynamics-apm#17]
The AppDynamics Partner doc site needs to be updated to reflect the two tiles that we have introduced.

Currently, https://docs.pivotal.io/partners/appdynamics/index.html gives the APM monitoring docs
https://docs.pivotal.io/partners/appdynamics-platform/index.html  gives the Platform monitoring docs.

Ideally, it should be a single doc landing page for AppDynamics which lists the following set of docs

https://docs.pivotal.io/partners/appdynamics-apm/index.html (for APM)
https://docs.pivotal.io/partners/appdynamics-platform/index.html (Platform)

**Comment by pavankrish123** [comment]
Hi @radhikapc : I don't think this is possible, The two should be treated as different projects (as they are)

I believe there is a different CI is tied to individual project.  The most we could do is to provide a reference link from each project. 

Thanks.
Pavan
